### ISSUE TITLE
KeyError: 'core'

### ISSUE THREAD

**Issue by yisampi** [jackaduma/LAS_Mandarin_PyTorch#2]
python main.py --config ./config/aishell_asr_example_lstm4atthead1.yaml --test

Using test mode

Traceback (most recent call last):
  File "main.py", line 83, in <module>
    solver = Solver(config, paras, mode)
  File "/data02/sam.yi/LAS_Mandarin_PyTorch/test_asr.py", line 24, in __init__
    super().__init__(config, paras, mode)
  File "/data02/sam.yi/LAS_Mandarin_PyTorch/core/solver.py", line 75, in __init__
    open(config['core']['config'], 'r'), Loader=yaml.FullLoader)
KeyError: 'core'

**Comment by durian1023** [comment]
Have you solved it? I have the same problem

**Comment by dayu1979** [comment]
I have the same problem

**Comment by guggugg** [comment]
Has anyone solved this problem

**Comment by yhz5256** [comment]
> Have you solved it? I have the same problem
I have the same problem

**Comment by Ko-vey** [comment]
This is probably a yaml file, but I can not find it in the project folder as well.
